package BatallaNaval;

import static BatallaNaval.Escenario.Bloque;
import static BatallaNaval.Escenario.Agua;
import static BatallaNaval.Escenario.Tocado;
import static BatallaNaval.Escenario.cantidadFilas;
import static BatallaNaval.Escenario.cantidadColumnas;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author AgustinLebed
 */
public class FormularioPrincipal extends javax.swing.JFrame {

 
         //Jugador 1
        static public Escenario escenarioJ1 = new Escenario();    
         //jugador2
         static public Escenario escenarioJ2 = new Escenario(); 
  
         
    /**
     * Creates new form FormularioPrincipal
     */
    public FormularioPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        Panel_jugador2 = new javax.swing.JPanel();
        Label_nick = new javax.swing.JLabel();
        label_crucero = new javax.swing.JLabel();
        Label_destructor = new javax.swing.JLabel();
        label_portavionesj2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        pantallaJuegoj2 = new javax.swing.JTable();
        panelregistroJ2 = new javax.swing.JPanel();
        texto_nombrej2 = new javax.swing.JTextField();
        texto_destructorj2 = new javax.swing.JTextField();
        texto_cruceroj2 = new javax.swing.JTextField();
        texto_portaavionesj2 = new javax.swing.JTextField();
        boton_cargarj2 = new javax.swing.JButton();
        panelInfoJ2 = new javax.swing.JPanel();
        labelNickJ2 = new javax.swing.JLabel();
        labelDestructorJ2 = new javax.swing.JLabel();
        labelCruceroJ2 = new javax.swing.JLabel();
        labelPortaavionesJ2 = new javax.swing.JLabel();
        labelHundidosJ2 = new javax.swing.JLabel();
        labelDestructorDañosJ2 = new javax.swing.JLabel();
        labelCruceroDañosJ2 = new javax.swing.JLabel();
        labelPortaavionesDañosJ2 = new javax.swing.JLabel();
        boton_salir = new javax.swing.JButton();
        Panel_jugador3 = new javax.swing.JPanel();
        Label_nick1 = new javax.swing.JLabel();
        label_crucero1 = new javax.swing.JLabel();
        Label_destructor1 = new javax.swing.JLabel();
        label_portavionesj3 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        pantallaJuegoj1 = new javax.swing.JTable();
        panelRegistroJ1 = new javax.swing.JPanel();
        texto_nombrej1 = new javax.swing.JTextField();
        texto_destructorj1 = new javax.swing.JTextField();
        texto_cruceroj1 = new javax.swing.JTextField();
        texto_portaavionesj1 = new javax.swing.JTextField();
        boton_cargarj1 = new javax.swing.JButton();
        panelInfoJ1 = new javax.swing.JPanel();
        labelNick = new javax.swing.JLabel();
        labelDestructorJ1 = new javax.swing.JLabel();
        labelCruceroJ1 = new javax.swing.JLabel();
        labelPortaavionesJ1 = new javax.swing.JLabel();
        labelHundidosJ1 = new javax.swing.JLabel();
        labelDestructorDañosJ1 = new javax.swing.JLabel();
        labelCruceroDañosJ1 = new javax.swing.JLabel();
        labelPortaavionesDañosJ1 = new javax.swing.JLabel();
        panelInfoJ3 = new javax.swing.JPanel();
        labelPuntajeJ1 = new javax.swing.JLabel();
        labelDestructorCoordXJ1 = new javax.swing.JLabel();
        labelCruceroCoordXJ1 = new javax.swing.JLabel();
        labelPortaavionesCoordXJ1 = new javax.swing.JLabel();
        labelDestructorCoordYJ1 = new javax.swing.JLabel();
        labelCruceroCoordYJ1 = new javax.swing.JLabel();
        labelPortaavionesCoordYJ1 = new javax.swing.JLabel();
        botonJugar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(51, 51, 51));

        jLabel1.setFont(new java.awt.Font("Dialog", 0, 48)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Batalla naval");

        Label_nick.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        Label_nick.setText("NICK");

        label_crucero.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        label_crucero.setText("Nombre del crucero");

        Label_destructor.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        Label_destructor.setText("Nombre del destructor");

        label_portavionesj2.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        label_portavionesj2.setText("Nombre del portaaviones");

        pantallaJuegoj2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        pantallaJuegoj2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        pantallaJuegoj2.setGridColor(new java.awt.Color(204, 204, 204));
        pantallaJuegoj2.setRowHeight(25);
        pantallaJuegoj2.setSelectionBackground(new java.awt.Color(255, 255, 255));
        pantallaJuegoj2.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        pantallaJuegoj2.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        pantallaJuegoj2.setShowGrid(true);
        pantallaJuegoj2.setUpdateSelectionOnSort(false);
        jScrollPane1.setViewportView(pantallaJuegoj2);
        if (pantallaJuegoj2.getColumnModel().getColumnCount() > 0) {
            pantallaJuegoj2.getColumnModel().getColumn(0).setResizable(false);
            pantallaJuegoj2.getColumnModel().getColumn(1).setResizable(false);
            pantallaJuegoj2.getColumnModel().getColumn(2).setResizable(false);
            pantallaJuegoj2.getColumnModel().getColumn(3).setResizable(false);
            pantallaJuegoj2.getColumnModel().getColumn(4).setResizable(false);
            pantallaJuegoj2.getColumnModel().getColumn(5).setResizable(false);
            pantallaJuegoj2.getColumnModel().getColumn(6).setResizable(false);
            pantallaJuegoj2.getColumnModel().getColumn(7).setResizable(false);
            pantallaJuegoj2.getColumnModel().getColumn(8).setResizable(false);
            pantallaJuegoj2.getColumnModel().getColumn(9).setResizable(false);
            pantallaJuegoj2.getColumnModel().getColumn(10).setResizable(false);
            pantallaJuegoj2.getColumnModel().getColumn(11).setResizable(false);
            pantallaJuegoj2.getColumnModel().getColumn(12).setResizable(false);
            pantallaJuegoj2.getColumnModel().getColumn(13).setResizable(false);
            pantallaJuegoj2.getColumnModel().getColumn(14).setResizable(false);
            pantallaJuegoj2.getColumnModel().getColumn(15).setResizable(false);
            pantallaJuegoj2.getColumnModel().getColumn(16).setResizable(false);
            pantallaJuegoj2.getColumnModel().getColumn(17).setResizable(false);
            pantallaJuegoj2.getColumnModel().getColumn(18).setResizable(false);
            pantallaJuegoj2.getColumnModel().getColumn(19).setResizable(false);
            pantallaJuegoj2.getColumnModel().getColumn(20).setResizable(false);
            pantallaJuegoj2.getColumnModel().getColumn(21).setResizable(false);
            pantallaJuegoj2.getColumnModel().getColumn(22).setResizable(false);
            pantallaJuegoj2.getColumnModel().getColumn(23).setResizable(false);
            pantallaJuegoj2.getColumnModel().getColumn(24).setResizable(false);
        }

        texto_nombrej2.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        texto_nombrej2.setText("a");
        texto_nombrej2.setMinimumSize(new java.awt.Dimension(5, 20));

        texto_destructorj2.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        texto_destructorj2.setText("a");
        texto_destructorj2.setMinimumSize(new java.awt.Dimension(5, 20));

        texto_cruceroj2.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        texto_cruceroj2.setText("a");
        texto_cruceroj2.setMinimumSize(new java.awt.Dimension(5, 20));
        texto_cruceroj2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                texto_cruceroj2ActionPerformed(evt);
            }
        });

        texto_portaavionesj2.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        texto_portaavionesj2.setText("a");
        texto_portaavionesj2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                texto_portaavionesj2ActionPerformed(evt);
            }
        });

        boton_cargarj2.setText("Cargar jugador");
        boton_cargarj2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_cargarj2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelregistroJ2Layout = new javax.swing.GroupLayout(panelregistroJ2);
        panelregistroJ2.setLayout(panelregistroJ2Layout);
        panelregistroJ2Layout.setHorizontalGroup(
            panelregistroJ2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelregistroJ2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(boton_cargarj2, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(70, 70, 70))
            .addGroup(panelregistroJ2Layout.createSequentialGroup()
                .addGroup(panelregistroJ2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(texto_nombrej2, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(texto_destructorj2, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(texto_cruceroj2, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(texto_portaavionesj2, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        panelregistroJ2Layout.setVerticalGroup(
            panelregistroJ2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelregistroJ2Layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addComponent(texto_nombrej2, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(texto_destructorj2, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(texto_cruceroj2, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(texto_portaavionesj2, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(67, 67, 67)
                .addComponent(boton_cargarj2, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 27, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout panelInfoJ2Layout = new javax.swing.GroupLayout(panelInfoJ2);
        panelInfoJ2.setLayout(panelInfoJ2Layout);
        panelInfoJ2Layout.setHorizontalGroup(
            panelInfoJ2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelInfoJ2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelInfoJ2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelNickJ2)
                    .addComponent(labelDestructorJ2)
                    .addComponent(labelCruceroJ2)
                    .addComponent(labelPortaavionesJ2))
                .addGap(59, 59, 59)
                .addGroup(panelInfoJ2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelHundidosJ2)
                    .addComponent(labelDestructorDañosJ2)
                    .addComponent(labelCruceroDañosJ2)
                    .addComponent(labelPortaavionesDañosJ2))
                .addContainerGap(86, Short.MAX_VALUE))
        );
        panelInfoJ2Layout.setVerticalGroup(
            panelInfoJ2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelInfoJ2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelInfoJ2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(panelInfoJ2Layout.createSequentialGroup()
                        .addComponent(labelHundidosJ2, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(labelDestructorDañosJ2, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(labelCruceroDañosJ2, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(labelPortaavionesDañosJ2, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelInfoJ2Layout.createSequentialGroup()
                        .addComponent(labelNickJ2, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(labelDestructorJ2, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(labelCruceroJ2, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(labelPortaavionesJ2, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(69, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout Panel_jugador2Layout = new javax.swing.GroupLayout(Panel_jugador2);
        Panel_jugador2.setLayout(Panel_jugador2Layout);
        Panel_jugador2Layout.setHorizontalGroup(
            Panel_jugador2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Panel_jugador2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 616, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Panel_jugador2Layout.createSequentialGroup()
                .addGap(0, 28, Short.MAX_VALUE)
                .addGroup(Panel_jugador2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(label_portavionesj2)
                    .addComponent(Label_nick, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Label_destructor)
                    .addComponent(label_crucero))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelregistroJ2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(panelInfoJ2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(122, 122, 122))
        );
        Panel_jugador2Layout.setVerticalGroup(
            Panel_jugador2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel_jugador2Layout.createSequentialGroup()
                .addGroup(Panel_jugador2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Panel_jugador2Layout.createSequentialGroup()
                        .addGap(61, 61, 61)
                        .addGroup(Panel_jugador2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(Panel_jugador2Layout.createSequentialGroup()
                                .addComponent(Label_nick)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(Label_destructor)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(label_crucero)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(label_portavionesj2)
                                .addGap(123, 123, 123))
                            .addComponent(panelregistroJ2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(Panel_jugador2Layout.createSequentialGroup()
                        .addGap(53, 53, 53)
                        .addComponent(panelInfoJ2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 332, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(174, 174, 174))
        );

        boton_salir.setText("Salir");
        boton_salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_salirActionPerformed(evt);
            }
        });

        Panel_jugador3.setPreferredSize(new java.awt.Dimension(747, 826));

        Label_nick1.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        Label_nick1.setText("NICK");

        label_crucero1.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        label_crucero1.setText("Nombre del crucero");

        Label_destructor1.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        Label_destructor1.setText("Nombre del destructor");

        label_portavionesj3.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        label_portavionesj3.setText("Nombre del portaaviones");

        pantallaJuegoj1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        pantallaJuegoj1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        pantallaJuegoj1.setGridColor(new java.awt.Color(204, 204, 204));
        pantallaJuegoj1.setRowHeight(25);
        pantallaJuegoj1.setSelectionBackground(new java.awt.Color(255, 255, 255));
        pantallaJuegoj1.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        pantallaJuegoj1.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        pantallaJuegoj1.setShowGrid(true);
        jScrollPane2.setViewportView(pantallaJuegoj1);

        panelRegistroJ1.setPreferredSize(new java.awt.Dimension(324, 225));

        texto_nombrej1.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        texto_nombrej1.setText("a");
        texto_nombrej1.setMinimumSize(new java.awt.Dimension(5, 20));

        texto_destructorj1.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        texto_destructorj1.setText("a");
        texto_destructorj1.setMinimumSize(new java.awt.Dimension(5, 20));

        texto_cruceroj1.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        texto_cruceroj1.setText("a");
        texto_cruceroj1.setMinimumSize(new java.awt.Dimension(5, 20));

        texto_portaavionesj1.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        texto_portaavionesj1.setText("a");
        texto_portaavionesj1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                texto_portaavionesj1ActionPerformed(evt);
            }
        });

        boton_cargarj1.setText("Cargar jugador");
        boton_cargarj1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_cargarj1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelRegistroJ1Layout = new javax.swing.GroupLayout(panelRegistroJ1);
        panelRegistroJ1.setLayout(panelRegistroJ1Layout);
        panelRegistroJ1Layout.setHorizontalGroup(
            panelRegistroJ1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRegistroJ1Layout.createSequentialGroup()
                .addGroup(panelRegistroJ1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(texto_nombrej1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(texto_cruceroj1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(texto_destructorj1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(texto_portaavionesj1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(boton_cargarj1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 27, Short.MAX_VALUE))
        );
        panelRegistroJ1Layout.setVerticalGroup(
            panelRegistroJ1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRegistroJ1Layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(texto_nombrej1, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(texto_destructorj1, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(texto_cruceroj1, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(texto_portaavionesj1, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(boton_cargarj1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(75, 75, 75))
        );

        javax.swing.GroupLayout panelInfoJ1Layout = new javax.swing.GroupLayout(panelInfoJ1);
        panelInfoJ1.setLayout(panelInfoJ1Layout);
        panelInfoJ1Layout.setHorizontalGroup(
            panelInfoJ1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelInfoJ1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelInfoJ1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelNick)
                    .addComponent(labelDestructorJ1)
                    .addComponent(labelCruceroJ1)
                    .addComponent(labelPortaavionesJ1))
                .addGap(59, 59, 59)
                .addGroup(panelInfoJ1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelHundidosJ1)
                    .addComponent(labelDestructorDañosJ1)
                    .addComponent(labelCruceroDañosJ1)
                    .addComponent(labelPortaavionesDañosJ1))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelInfoJ1Layout.setVerticalGroup(
            panelInfoJ1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelInfoJ1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelInfoJ1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(panelInfoJ1Layout.createSequentialGroup()
                        .addComponent(labelHundidosJ1, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(labelDestructorDañosJ1, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(labelCruceroDañosJ1, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(labelPortaavionesDañosJ1, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelInfoJ1Layout.createSequentialGroup()
                        .addComponent(labelNick, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(labelDestructorJ1, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(labelCruceroJ1, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(labelPortaavionesJ1, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(99, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout panelInfoJ3Layout = new javax.swing.GroupLayout(panelInfoJ3);
        panelInfoJ3.setLayout(panelInfoJ3Layout);
        panelInfoJ3Layout.setHorizontalGroup(
            panelInfoJ3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelInfoJ3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelInfoJ3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelDestructorCoordXJ1)
                    .addComponent(labelCruceroCoordXJ1)
                    .addComponent(labelPortaavionesCoordXJ1)
                    .addComponent(labelPuntajeJ1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(62, 62, 62)
                .addGroup(panelInfoJ3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelDestructorCoordYJ1)
                    .addComponent(labelCruceroCoordYJ1)
                    .addComponent(labelPortaavionesCoordYJ1))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelInfoJ3Layout.setVerticalGroup(
            panelInfoJ3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelInfoJ3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelPuntajeJ1, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelInfoJ3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(panelInfoJ3Layout.createSequentialGroup()
                        .addComponent(labelDestructorCoordYJ1, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(labelCruceroCoordYJ1, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(labelPortaavionesCoordYJ1, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelInfoJ3Layout.createSequentialGroup()
                        .addComponent(labelDestructorCoordXJ1, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(labelCruceroCoordXJ1, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(labelPortaavionesCoordXJ1, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(70, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout Panel_jugador3Layout = new javax.swing.GroupLayout(Panel_jugador3);
        Panel_jugador3.setLayout(Panel_jugador3Layout);
        Panel_jugador3Layout.setHorizontalGroup(
            Panel_jugador3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel_jugador3Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(Panel_jugador3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Panel_jugador3Layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 739, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(Panel_jugador3Layout.createSequentialGroup()
                        .addGroup(Panel_jugador3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Label_nick1, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Label_destructor1)
                            .addComponent(label_crucero1)
                            .addComponent(label_portavionesj3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(panelRegistroJ1, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(panelInfoJ1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(panelInfoJ3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(236, 236, 236))))
        );
        Panel_jugador3Layout.setVerticalGroup(
            Panel_jugador3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel_jugador3Layout.createSequentialGroup()
                .addGroup(Panel_jugador3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Panel_jugador3Layout.createSequentialGroup()
                        .addGap(67, 67, 67)
                        .addComponent(Label_nick1)
                        .addGap(15, 15, 15)
                        .addComponent(Label_destructor1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(label_crucero1)
                        .addGap(17, 17, 17)
                        .addComponent(label_portavionesj3)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Panel_jugador3Layout.createSequentialGroup()
                        .addGap(0, 23, Short.MAX_VALUE)
                        .addGroup(Panel_jugador3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(panelRegistroJ1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 283, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Panel_jugador3Layout.createSequentialGroup()
                                .addGroup(Panel_jugador3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(panelInfoJ3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(panelInfoJ1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(42, 42, 42)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 331, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(180, 180, 180))
        );

        botonJugar.setText("Jugar");
        botonJugar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonJugarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(698, 698, 698)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 332, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(718, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(Panel_jugador3, javax.swing.GroupLayout.PREFERRED_SIZE, 809, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Panel_jugador2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(botonJugar, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(boton_salir, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Panel_jugador3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Panel_jugador2, javax.swing.GroupLayout.PREFERRED_SIZE, 653, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(boton_salir, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botonJugar, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        jLabel1.getAccessibleContext().setAccessibleName("Batalla Naval");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void texto_portaavionesj2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_texto_portaavionesj2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_texto_portaavionesj2ActionPerformed

    private void boton_salirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_salirActionPerformed
        // TODO add your handling code here:
        System.exit(WIDTH);
    }//GEN-LAST:event_boton_salirActionPerformed

    private void texto_portaavionesj1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_texto_portaavionesj1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_texto_portaavionesj1ActionPerformed

    private void boton_cargarj1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_cargarj1ActionPerformed
        // TODO add your handling code here:
        
        
        if (texto_nombrej1.getText().isBlank() || texto_destructorj1.getText().isBlank() || texto_cruceroj1.getText().isEmpty() || texto_portaavionesj1.getText().isBlank())
        {
            JOptionPane.showMessageDialog(null,"Complete todos los campos");
        }else
        {
            escenarioJ1.getJugador().setNick(texto_nombrej1.getText());
            escenarioJ1.getJugador().getDestructor().setNombre(texto_destructorj1.getText());
            escenarioJ1.getJugador().getCrucero().setNombre(texto_cruceroj1.getText());
            escenarioJ1.getJugador().getPortaaviones().setNombre(texto_portaavionesj1.getText());
            JOptionPane.showMessageDialog(null,"Jugador cargado");
            panelRegistroJ1.setVisible(false);
            
            
            labelNick.setText(escenarioJ1.getJugador().getNick());
            labelDestructorJ1.setText( escenarioJ1.getJugador().getDestructor().getNombre());
            labelCruceroJ1.setText(escenarioJ1.getJugador().getCrucero().getNombre());
            labelPortaavionesJ1.setText(escenarioJ1.getJugador().getPortaaviones().getNombre());
            labelHundidosJ1.setText(escenarioJ1.getJugador().getHundidosString());
            labelDestructorDañosJ1.setText(escenarioJ1.getJugador().getDestructor().getDaniosString());
            labelCruceroDañosJ1.setText( escenarioJ1.getJugador().getCrucero().getDaniosString());
            labelPortaavionesDañosJ1.setText(escenarioJ1.getJugador().getPortaaviones().getDaniosString());
            
            
        }
    }//GEN-LAST:event_boton_cargarj1ActionPerformed
    
    
    private void boton_cargarj2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_cargarj2ActionPerformed
        // TODO add your handling code here:
        if (texto_nombrej2.getText().isBlank() || texto_destructorj2.getText().isBlank()|| texto_cruceroj2.getText().isBlank() || texto_portaavionesj2.getText().isBlank())
                {
                    JOptionPane.showMessageDialog(null,"Complete todos los campos");
                }else{
        
            escenarioJ2.getJugador().setNick(texto_nombrej2.getText());
            escenarioJ2.getJugador().getDestructor().setNombre(texto_destructorj2.getText());
            escenarioJ2.getJugador().getCrucero().setNombre(texto_cruceroj2.getText());
            escenarioJ2.getJugador().getPortaaviones().setNombre(texto_portaavionesj2.getText());
            JOptionPane.showMessageDialog(null,"Jugador cargado");
            panelregistroJ2.setVisible(false);
            
            labelNickJ2.setText(escenarioJ2.getJugador().getNick());
            labelDestructorJ2.setText(escenarioJ2.getJugador().getDestructor().getNombre());
            labelCruceroJ2.setText(escenarioJ2.getJugador().getCrucero().getNombre());
            labelPortaavionesJ2.setText(escenarioJ2.getJugador().getPortaaviones().getNombre());
            labelHundidosJ2.setText(escenarioJ2.getJugador().getHundidosString());
            labelDestructorDañosJ2.setText(escenarioJ2.getJugador().getDestructor().getDaniosString());
            labelCruceroDañosJ2.setText(escenarioJ2.getJugador().getCrucero().getDaniosString());
            labelPortaavionesDañosJ2.setText(escenarioJ2.getJugador().getPortaaviones().getDaniosString());
        }
  
    }//GEN-LAST:event_boton_cargarj2ActionPerformed

    
    
    public void pasarDeMatrizATabla(Escenario escenario, int turno)
    {
        int i,j;
        
        for (i=0; i<escenario.getCantidadFilas()-2; i++)
        {
            for(j=0; j<escenario.getCantidadColumnas()-2; j++)
            {
                if(turno==1)
                {   
                    pantallaJuegoj1.setValueAt(escenario.getPantallaJuegoString(i, j), j, turno);
                }
                
            }
        }
       
    }
    
    private void botonJugarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonJugarActionPerformed
        // TODO add your handling code here:
        DefaultTableModel aux = new DefaultTableModel();
        if(texto_nombrej2.getText().isBlank() || texto_destructorj2.getText().isBlank()|| texto_cruceroj2.getText().isBlank() || texto_portaavionesj2.getText().isBlank()
           || texto_nombrej1.getText().isBlank() || texto_destructorj1.getText().isBlank() || texto_cruceroj1.getText().isEmpty() || texto_portaavionesj1.getText().isBlank())
            {
                 JOptionPane.showMessageDialog(null,"Complete los registros de los jugadores");
            }
        else
        {
           
          escenarioJ1.rellenarEscenario();
          // escenarioJ1.dibujarBarco(escenarioJ1.getJugador().getDestructor());
           //escenarioJ1.dibujarBarco(escenarioJ1.getJugador().getCrucero());
           //escenarioJ1.dibujarBarco(escenarioJ1.getJugador().getPortaaviones());
           labelDestructorCoordXJ1.setText(escenarioJ1.getJugador().getDestructor().getCoordXString());
           labelDestructorCoordYJ1.setText(escenarioJ1.getJugador().getDestructor().getCoordYString());
           labelCruceroCoordXJ1.setText(escenarioJ1.getJugador().getCrucero().getCoordXString());
           labelCruceroCoordYJ1.setText(escenarioJ1.getJugador().getCrucero().getCoordYString());
           labelPortaavionesCoordXJ1.setText(escenarioJ1.getJugador().getPortaaviones().getCoordXString());
            labelPortaavionesCoordYJ1.setText(escenarioJ1.getJugador().getPortaaviones().getCoordYString());
           
           
           
           escenarioJ2.rellenarEscenario();
           //escenarioJ2.dibujarBarco(escenarioJ2.getJugador().getDestructor());
           //escenarioJ2.dibujarBarco(escenarioJ2.getJugador().getCrucero());
           //escenarioJ2.dibujarBarco(escenarioJ2.getJugador().getPortaaviones());
        
            pasarDeMatrizATabla(escenarioJ1, 1);
           //botonJugar.setVisible(false);
           
           escenarioJ1.imprimirEscenario();
           escenarioJ2.imprimirEscenario();
        }
        
    }//GEN-LAST:event_botonJugarActionPerformed

    private void texto_cruceroj2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_texto_cruceroj2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_texto_cruceroj2ActionPerformed
    //se eligen las coordenadas aleatoriamente del barco que se pase 
   
    
    private void actualizarLabels()
    {
            labelHundidosJ1.setText(escenarioJ1.getJugador().getHundidosString());
            labelDestructorDañosJ1.setText(escenarioJ1.getJugador().getDestructor().getDaniosString());
            labelCruceroDañosJ1.setText(escenarioJ1.getJugador().getCrucero().getDaniosString());
            labelPortaavionesDañosJ1.setText(escenarioJ1.getJugador().getPortaaviones().getDaniosString());
            
            labelHundidosJ2.setText(escenarioJ2.getJugador().getHundidosString());
            labelDestructorDañosJ2.setText(escenarioJ2.getJugador().getDestructor().getDaniosString());
            labelCruceroDañosJ2.setText(escenarioJ2.getJugador().getCrucero().getDaniosString());
            labelPortaavionesDañosJ2.setText(escenarioJ2.getJugador().getPortaaviones().getDaniosString());
        
    }

   
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {//*********************************Main*******************************
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormularioPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormularioPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormularioPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormularioPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormularioPrincipal().setVisible(true);
            }
        });
       
       
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Label_destructor;
    private javax.swing.JLabel Label_destructor1;
    private javax.swing.JLabel Label_nick;
    private javax.swing.JLabel Label_nick1;
    private javax.swing.JPanel Panel_jugador2;
    private javax.swing.JPanel Panel_jugador3;
    private javax.swing.JButton botonJugar;
    private javax.swing.JButton boton_cargarj1;
    private javax.swing.JButton boton_cargarj2;
    private javax.swing.JButton boton_salir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel labelCruceroCoordXJ1;
    private javax.swing.JLabel labelCruceroCoordYJ1;
    private javax.swing.JLabel labelCruceroDañosJ1;
    private javax.swing.JLabel labelCruceroDañosJ2;
    private javax.swing.JLabel labelCruceroJ1;
    private javax.swing.JLabel labelCruceroJ2;
    private javax.swing.JLabel labelDestructorCoordXJ1;
    private javax.swing.JLabel labelDestructorCoordYJ1;
    private javax.swing.JLabel labelDestructorDañosJ1;
    private javax.swing.JLabel labelDestructorDañosJ2;
    private javax.swing.JLabel labelDestructorJ1;
    private javax.swing.JLabel labelDestructorJ2;
    private javax.swing.JLabel labelHundidosJ1;
    private javax.swing.JLabel labelHundidosJ2;
    private javax.swing.JLabel labelNick;
    private javax.swing.JLabel labelNickJ2;
    private javax.swing.JLabel labelPortaavionesCoordXJ1;
    private javax.swing.JLabel labelPortaavionesCoordYJ1;
    private javax.swing.JLabel labelPortaavionesDañosJ1;
    private javax.swing.JLabel labelPortaavionesDañosJ2;
    private javax.swing.JLabel labelPortaavionesJ1;
    private javax.swing.JLabel labelPortaavionesJ2;
    private javax.swing.JLabel labelPuntajeJ1;
    private javax.swing.JLabel label_crucero;
    private javax.swing.JLabel label_crucero1;
    private javax.swing.JLabel label_portavionesj2;
    private javax.swing.JLabel label_portavionesj3;
    private javax.swing.JPanel panelInfoJ1;
    private javax.swing.JPanel panelInfoJ2;
    private javax.swing.JPanel panelInfoJ3;
    private javax.swing.JPanel panelRegistroJ1;
    private javax.swing.JPanel panelregistroJ2;
    private javax.swing.JTable pantallaJuegoj1;
    private javax.swing.JTable pantallaJuegoj2;
    private javax.swing.JTextField texto_cruceroj1;
    private javax.swing.JTextField texto_cruceroj2;
    private javax.swing.JTextField texto_destructorj1;
    private javax.swing.JTextField texto_destructorj2;
    private javax.swing.JTextField texto_nombrej1;
    private javax.swing.JTextField texto_nombrej2;
    private javax.swing.JTextField texto_portaavionesj1;
    private javax.swing.JTextField texto_portaavionesj2;
    // End of variables declaration//GEN-END:variables
}
